# =========================================================
# Section: ZMK Studio
# ---------------------------------------------------------
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# =========================================================
# Section: Connection Performance
# ---------------------------------------------------------
# 再接続高速化：接続間隔を短縮（6〜12ms)
#CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
#CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

# BLE 安定性確保（1Mbps固定）
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# 動き出し遅延ゼロ (Wake-up Latency対策)
#CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# =========================================================
# Section: BLE TX Power
# ---------------------------------------------------------
# 出力を +8dBm に設定（電池寿命と通信安定性のバランス）
CONFIG_BT_CTLR_TX_PWR_PLUS_8=n

# =========================================================
# Section: Battery & System
# ---------------------------------------------------------
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_SLEEP=n
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900

# ==========================================
# Eager Debouncing (キー反応速度アップ)
# ==========================================
# キー入力の反応を高速化
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3
